---
name: Statistics-ANOVA
version: 0.07
author:
  - 'Roderick Garton <rgarton@cpan.org>'
abstract: Parametric/nonparametric 1-way analyses of variance for means-comparisons and clusterings per differences/trends over independent or repeated measures of groups/levels
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Algorithm::Combinatorics: 0.23
  Math::Cephes: 0.43
  Scalar::Util: 1.18
  Statistics::DependantTTest: 0.03
  Statistics::Descriptive: 2.6
  Statistics::Lite: 3.2
  Statistics::TTest: 1.1
  Test::More: 0.0
configure_requires:
  Module::Build: 0.340201
provides:
  Statistics::ANOVA:
    file: lib/Statistics/ANOVA.pm
    version: 0.07
generated_by: Module::Build version 0.340201
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
