---
abstract: 'Parametric and nonparametric 1-way analyses of variance for means-comparison and clustering per differences/trends over independent or repeated measures of groups or levels'
author:
  - 'Roderick Garton <rgarton@cpan.org>'
build_requires:
  Algorithm::Combinatorics: 0.23
  Math::Cephes: 0.43
  Scalar::Util: 1.18
  Statistics::DependantTTest: 0.03
  Statistics::Descriptive: 2.6
  Statistics::Lite: 3.2
  Statistics::TTest: 1.1
  Test::More: 0.0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Statistics-ANOVA
provides:
  Statistics::ANOVA:
    file: lib/Statistics/ANOVA.pm
    version: 0.08
resources:
  license: http://dev.perl.org/licenses/
version: 0.08
